version: '3'

services:
  mysql-docker-container:
    image: mysql/mysql-server:latest
    container_name: mysql-docker
    networks:
      - mon-net
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: sergey
      MYSQL_DATABASE: photo_app
      MYSQL_USER: sergey
      MYSQL_PASSWORD: sergey
    #healthcheck:
     # test: ["CMD", "curl", "-f", "http://localhost:8000"]
      #interval: 10s
      #timeout: 5s
      #retries: 3

  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mysql-docker-container
      #condition: service_healthy 
    networks:
      - mon-net
    restart: always 
networks:
  mon-net:
    driver: bridge


